### ISSUE TITLE
Creation of a programming language based on Blade.

### ISSUE THREAD

**Issue by Zuygui** [blade-lang/blade#108]
Hello,

We want to create a programming language for professional, personal and utility needs. We want to base ourselves on your language, which we find very interesting in its simplicity and speed. Can we fork your project? Or take over the project for free?

Cordially,
Zuygui

**Comment by Zuygui** [comment]
This would also include the use of the package manager. The latter, we can code it ourselves.

**Comment by mcfriend99** [comment]
Hi @Zuygui,

Firstly, I want to thank you for your interest in Blade. 

As an open-source project, Blade is actively seeking dedicated contributors to the project and a contribution like a package manager will go a long way as well as significant contribution of core library/modules (which will be near impossible with the number of current contributors).

If you do have the resource and time, I'll counter that rather than creating a new programming language off Blade which itself is still very new and young, why not become an active contributor to the development of Blade. This will give you the opportunity to develop new features and libraries that will reflect in Blade as a language and hence, you'll achieve the same objective you initially have without having to create a new language.

I believe the best thing for Blade now is to have more libraries, a package manager and better distinguishing features. Also, while now yet documented, developments to allow easy package management which package managers can easily leverage is already done in the `dev` branch and will become part of the next release.

Also, since there has been significant contributions by other people into the project, the decision is beyond what I can make alone.

Regards

**Comment by Zuygui** [comment]
Our language would be purely a fork of blade, we will credit you but we want to remain independent to offer a language based on blade. We would like to start from the current blade source code and go independently.

**Comment by mcfriend99** [comment]
@Zuygui While I still do not see any benefits to Blade in what you are proposing, Blade's license is MIT and you do not need any permission to fork it. However, do you have any plans to send enhancements upstream??

**Comment by Zuygui** [comment]
We will use our fork (we modify the language according to our needs) in order to develop our applications as well as our software. If a security bug is found, we will fix it and send you the bug. You have no advantage in it, but we really need this fork.

and I did not understand the license because I am French.

**Comment by Zuygui** [comment]
If you want check the source code on based blade langage. Just go [here](https://github.com/foxy-lang) !

**Comment by Zuygui** [comment]
Else, dou you want support the Foxy Project ? I want transform Blade yo a simple language for begginers.

**Comment by mcfriend99** [comment]
Noted. But this isn't looking like a clone. Looks like another project using the same codebase.

Like I said earlier, Blade is licensed MIT. Just to clarify of you, you'll need to retain a copy of the license in your work. That's all that is required.

Regards.

**Comment by mcfriend99** [comment]
And while the codebase is MIT, the language itself isn't. This means that you can't retain the same README, description and all related items.

**Comment by Zuygui** [comment]
> And while the codebase is MIT, the language itself isn't. This means that you can't retain the same README, description and all related items.

What do you mean ?

**Comment by Zuygui** [comment]
> Noted. But this isn't looking like a clone. Looks like another project using the same codebase.
> 
> Like I said earlier, this Blade implementation is licensed MIT. Just to clarify of you, you'll need to retain a copy of the license in your work. That's all that is required.
> 
> Regards.

We want to start from the current version of blade in order to branch off to a totally different release. I don't understand all your vocabulary because I'm French and the translator sometimes bugs ^^
