### ISSUE TITLE
Remove REPL `"nil"` printing

### ISSUE THREAD

**Issue by BenStigsen** [blade-lang/blade#73]
## Is your feature request related to a problem? Please describe.
`print(10)` in the REPL outputs `10nil`
It does not look nice when printing, that it is followed by `nil`.

## Describe the solution you'd like
`print(10)` should print `10` and not include `nil`.

This can be fixed by changing:
https://github.com/blade-lang/blade/blob/main/src/vm.c#L1549-L1553

Currently this is the code:
```c
if (vm->is_repl) {
  echo_value(peek(vm, 0));
} else {
  print_value(peek(vm, 0));
}
```
I propose:
```c
if (vm->is_repl) {
  // maybe have a variable to avoid peeking twice
  if (!IS_NIL(peek(vm, 0))) {
    echo_value(peek(vm, 0));
  }
} else {
  print_value(peek(vm, 0));
}
```

I'm curious as to why this is a thing. Is this a bug or is it for something like debugging? If wanted I can go ahead and PR this.

**Comment by mcfriend99** [comment]
The proposed solution and the lines of code highlighted has nothing to do with the problem. The difference between `print_value` and `echo_value` is that echo value wraps strings in appropriate quotations for easy presentation in the REPL.

What you are seeing is a side effect of the REPL attempting to print the result of the evaluation of the `print()` function. As the print function doesn't return any value, it implicitly return `nil` because every function returns a value in Blade and the default is not override by the `return` keyword is `nil`.

I've also been considering making the default return value for a function `empty`. Represented internally by the VM as `EMPTY_VAL`. This will cure this side effect. But at the same time, I don't think the language will benefit anything from having the ability to create the type `empty` as it cannot be used in any expression. It will also prevent us from being able to write code will the following:

```
def call(fn) {
  return 'str ${fn()}'
}

echo call(|| {})   # echoes 'str '
```

Though now I think about it, there is another way to cure this side effect. I'll take this up right away in the dev branch and see how it turns out.

**Comment by mcfriend99** [comment]
Another possible solution will be to add a newline in the `print()` native function implementation if `vm->is_repl == true`.

**Comment by mcfriend99** [comment]
Try building from the branch [defualt-return-as-empty](https://github.com/blade-lang/blade/tree/defualt-return-as-empty) and let me know if it addresses the side effect.

**Comment by BenStigsen** [comment]
Yep, that seems to fix the `nil` printing.

**Comment by mcfriend99** [comment]
Ok. I'm making the change language wide and once completed will close this ticket.
